### ISSUE TITLE
Fatal exception

### ISSUE THREAD

**Issue by omaflak** [1gravity/Android-ContactPicker#16]
Hello! I'm on Android 7.1.1 and I'm getting this error with your lib:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{me.aflak.myapp/com.onegravity.contactpicker.core.ContactPickerActivity}: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class android.support.design.widget.TabLayout
```

Do you know why is this happening ?
Thanks!

**Comment by 1gravity** [comment]
Please read the readme part about theming and define the attributes:

Theming

The library supports a dark and a light theme out-of-the-box. In order to do that, it defines a couple of custom attributes in attrs.xml. To integrate the contact picker in your app, you need to either extend one of the contact picker themes (ContactPicker_Theme_Light / ContactPicker_Theme_Dark) or define the custom attributes in your own theme.
