### ISSUE TITLE
ActionBar Menu

### ISSUE THREAD

**Issue by techlectdinesh** [1gravity/Android-ContactPicker#18]
I am unable to show all three Menu item on action bar. it shows only 2 Search and Check all either Search and OK.

**Comment by stitch9108** [comment]
I too have face this issue. It appears to only happen on small devices like the Galaxy SIII mini running API 16 (didn't test 17 and 18). Only the Search and Select All icons are showing. Putting the phone in landscape doesn't solve the issue. 
A API 24 emulator displays the three dots menu button instead of the Select All one which opens the menu with the Select All and OK entries.

@1gravity could you please fix this? Thanks a lot

**Comment by 1gravity** [comment]
very likely due to the fact that these devices have a dedicated menu button which would show all overflowing menu items when pressed

**Comment by stitch9108** [comment]
Actually yes. The Ok button is accessible using the hardware menu button on a API 16 Nexus One Emulator. However, using a API 24 Nexus One Emulator, the overflow is accessible from the app bar and the hardware button.

The OK button being the most important one, I think it would be better if it was always accessible (first menu entry). I think people won't press the hardware button most of the time. This would be a very simple fix if you don't have the time to dig in and find a way to display the 3-dots button for this kind of device.

Thanks for answering this quickly and thanks for the lib!

**Comment by 1gravity** [comment]
There's a way to show the overflow button even on devices with a dedicated menu button but it violates Android design guidelines (there's a lot of discussions about that on SO, e.g. here http://stackoverflow.com/a/9287015/534471) so I'm not going down that road.

d1445a2f2bbb2f27b8f36bf3eea21413d097d5df closes this issue.
