### ISSUE TITLE
Example of creating a custom theme?

### ISSUE THREAD

**Issue by retorquere** [1gravity/Android-ContactPicker#2]
I'm looking to integrate this picker in an existing app, so I'd like to match its style. Is there an example of how to create custom styles?

**Comment by 1gravity** [comment]
There are a couple of custom attributes defined in the attrs.xml but I can't really answer your question since I don't know what exactly you want to style. Examples aren't needed here, simply use what Android offers out of the box to customize the style: https://developer.android.com/guide/topics/ui/themes.html.
