### ISSUE TITLE
Showing Attribute undefined: 'cp_textColorPrimary'. Did you apply the correct theme?

### ISSUE THREAD

**Issue by chetanparmar95** [1gravity/Android-ContactPicker#23]
When i click on the button to start ContactPickerActivity, it is showing this error.

**Comment by 1gravity** [comment]
Please follow the readme:

####Theming

The library supports a dark and a light theme out-of-the-box. In order to do that, it defines a couple of custom attributes in attrs.xml. To integrate the contact picker in your app, you need to either extend one of the contact picker themes (ContactPicker_Theme_Light / ContactPicker_Theme_Dark) or define the custom attributes in your own theme.

**Comment by 1gravity** [comment]
There was a typo in one the the style definitions, try the new version 1.3.1
