### ISSUE TITLE
cp_textColorPrimary undefined

### ISSUE THREAD

**Issue by dashracer** [1gravity/Android-ContactPicker#24]
Hi, I've followed your steps but I got this error.

```
Attribute undefined:
"cp_textColorPrimary". Did you apply the correct theme?
```

What did I missed?

Thank You

**Comment by 1gravity** [comment]
Well you didn't follow all steps then:

####Theming

The library supports a dark and a light theme out-of-the-box. In order to do that, it defines a couple of custom attributes in attrs.xml. To integrate the contact picker in your app, you need to either extend one of the contact picker themes (ContactPicker_Theme_Light / ContactPicker_Theme_Dark) or define the custom attributes in your own theme.

**Comment by sana080** [comment]
Hello, 
I am implementing 
Intent(this, ContactPickerActivity.class).putExtra(ContactPickerActivity.EXTRA_THEME, R.style.ContactPicker_Theme_Light/R.style.ContactPicker_Theme_Dark)  or custom but still showing above error

**Comment by 1gravity** [comment]
There was a typo in one the the style definitions, try the new version 1.3.1
