### ISSUE TITLE
Possible to show only contacts with phone numbers

### ISSUE THREAD

**Issue by beejayzed** [1gravity/Android-ContactPicker#5]
Hi

Is it possible to filter which contacts are retrieved from the backend? Specifically, I'm interested in showing only contacts that have a cell phone number.

Thanks and Kind Regards

**Comment by 1gravity** [comment]
Check out the readContactDetails method in the ContactPickerActivity. It adds all phone numbers to the contact. Once the contacts are populated sortAndPostCopy is called. You could loop over the contacts in that method and eliminate those without a cell phone number before posting them to the ui.

You might want to remove these lines in readContacts(Cursor) because that would show all contacts before the details can be read so contacts might show then disappear if they have not cell phone number:
```
        if (count > 0) {
            sortAndPostCopy(mContacts);
        }

```

**Comment by beejayzed** [comment]
Thanks for the reply. Ended up changing the contactscontact query to only return results with the HAS_NUMBER flag.

**Comment by 1gravity** [comment]
That works too ;-)
